import slugify from 'slugify';
import type { PrismaClient } from '@prisma/client';
import type { World, VedaZone, Character } from '@satchit/shared';
import type { IAIProvider } from '../ai/index.js';
import { AnthropicProvider } from '../ai/providers/anthropic.js';
import { VedaService } from './VedaService.js';
import { NPCService } from './NPCService.js';

interface BootstrapResult {
  starterZones: VedaZone[];
  originSummary: string;
}

interface ActionResult {
  narration: string;
  zone: VedaZone;
  isNewZone: boolean;
}

export class WorldGeneratorService {
  private vedaService: VedaService;
  private npcService: NPCService;

  constructor(
    private prisma: PrismaClient,
    private ai: IAIProvider,
  ) {
    this.vedaService = new VedaService(prisma);
    this.npcService = new NPCService(prisma);
  }

  private providerFor(world: World): IAIProvider {
    if (world.anthropicApiKey) {
      return new AnthropicProvider(world.anthropicApiKey);
    }
    return this.ai;
  }

  /**
   * Bootstrap a newly created world: generate an origin summary and
   * 1–3 starter zones to give players somewhere to begin.
   */
  async bootstrapWorld(world: World): Promise<BootstrapResult> {
    const worldLore = await this.vedaService.listLore(world.id);

    const context = {
      world: {
        name: world.name,
        foundationalLaws: world.foundationalLaws,
        culturalTypologies: world.culturalTypologies,
      },
      worldLore,
    };

    const ai = this.providerFor(world);

    // Generate origin summary
    const originSummary = await ai.generate(
      `Write a vivid, 2-paragraph origin summary for the world of "${world.name}".
       This will be the first thing players see when they discover this world.
       Hint at mysteries, cultures, and the laws that shape existence here.`,
      context,
    );

    // Generate starter zone details
    const starterZoneShape = {
      zones: [
        {
          name: 'Zone Name',
          description: 'A short description of what this zone looks, sounds, and feels like.',
          rawContent: 'Detailed 2-paragraph AI narration a player would see upon entering.',
        },
      ],
    };

    const generated = await ai.generateStructured(
      `Create exactly 2 starting zones for the world of "${world.name}".
       These should feel distinct from each other and organically reflect the world's laws and cultures.`,
      context,
      starterZoneShape,
    );

    const zoneDefs = generated?.zones ?? [
      {
        name: 'The Beginning',
        description: 'Where all journeys start.',
        rawContent: `You stand at the threshold of ${world.name}. The air itself seems to carry the weight of ancient laws. Your journey begins here.`,
      },
    ];

    const starterZones: VedaZone[] = [];
    for (const def of zoneDefs) {
      // @ts-ignore: slugify CJS/ESM interop issue with NodeNext
      const slug = slugify(def.name, { lower: true, strict: true });
      const zone = await this.vedaService.saveZone({
        worldId: world.id,
        name: def.name,
        slug,
        description: def.description,
        rawContent: def.rawContent,
      });
      starterZones.push(zone);
    }

    return { starterZones, originSummary };
  }

  /**
   * Process a player action in a given zone.
   * Includes character context in the AI prompt so narration reflects who the player is.
   * Any NPCs generated by the AI are persisted as rich NPC records.
   */
  async processAction(
    world: World,
    currentZoneSlug: string,
    playerInput: string,
    playerId: string,
    character?: Character | null,
  ): Promise<ActionResult> {
    // Check Veda cache
    let zone = await this.vedaService.getZone(world.id, currentZoneSlug);
    const isNewZone = !zone;

    const worldLore = await this.vedaService.listLore(world.id);
    const nearbyZones = await this.vedaService.listZones(world.id);
    const npcsInZone = zone ? await this.npcService.listByZone(zone.id) : [];

    const ai = this.providerFor(world);

    const characterContext = character
      ? {
          name: character.name,
          species: character.species,
          race: character.race,
          gender: character.gender,
          traits: character.traits,
          skills: character.skills,
          abilities: character.abilities,
          physicalDescription: character.physicalDescription,
        }
      : null;

    const context = {
      world: {
        name: world.name,
        foundationalLaws: world.foundationalLaws,
        culturalTypologies: world.culturalTypologies,
      },
      character: characterContext,
      currentZone: zone ?? undefined,
      nearbyZones,
      worldLore,
      npcsPresent: npcsInZone.map((n) => ({
        name: n.name,
        disposition: n.disposition,
        traits: n.traits,
        physicalDescription: n.physicalDescription,
      })),
      playerInput,
    };

    if (isNewZone) {
      // Generate and persist new zone
      const slug = currentZoneSlug;
      const zoneName = slug
        .split('-')
        .map((w: string) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' ');

      const rawContent = await ai.generate(
        `The player has arrived in "${zoneName}" for the first time.
         Describe this location in vivid detail — what they see, hear, feel, and sense.
         Make it feel like a natural part of ${world.name}.${characterContext ? `\nThe player's character is ${characterContext.name}, a ${characterContext.species ?? 'being'} — let the description acknowledge their perspective if appropriate.` : ''}`,
        context,
      );

      zone = await this.vedaService.saveZone({
        worldId: world.id,
        name: zoneName,
        slug,
        description: rawContent.split('\n')[0] ?? rawContent.slice(0, 150),
        rawContent,
        discoveredById: playerId,
      });
    }

    // Generate narration for the player's specific action
    const characterLine = characterContext
      ? `The player's character is ${characterContext.name}${characterContext.species ? `, a ${characterContext.species}` : ''}${characterContext.traits.length ? ` with traits: ${characterContext.traits.join(', ')}` : ''}.`
      : '';

    const narration = await ai.generate(
      `The player is in "${zone!.name}" and does the following: "${playerInput}".
       ${characterLine}
       Narrate what happens, staying true to the world's laws and the zone's established details.
       If the player interacts with an NPC, reflect that NPC's disposition and personality.`,
      { ...context, currentZone: zone },
    );

    // Attempt to extract and persist any new NPCs mentioned in the narration
    await this.extractAndPersistNPCs(world, zone!, narration, ai);

    // Record the event in the Veda
    await this.vedaService.saveEvent({
      worldId: world.id,
      description: `${character?.name ?? `Player ${playerId}`} in ${zone!.name}: "${playerInput}"`,
      participantIds: [playerId],
    });

    return { narration, zone: zone!, isNewZone };
  }

  /**
   * Ask the AI to extract any NPCs from the narration and persist them
   * as both VedaEntity records and rich NPC records.
   */
  private async extractAndPersistNPCs(
    world: World,
    zone: VedaZone,
    narration: string,
    ai: IAIProvider,
  ): Promise<void> {
    try {
      const npcShape = {
        npcs: [
          {
            name: 'NPC name',
            species: 'species or null',
            race: 'race or null',
            gender: 'gender or null',
            physicalDescription: 'brief physical description',
            traits: ['personality trait'],
            disposition: 'friendly | neutral | wary | hostile',
            backstory: 'one sentence backstory or null',
          },
        ],
      };

      const extracted = await ai.generateStructured(
        `Read this narration and extract any named NPCs (people, creatures with names, significant beings) who appear.
         Only include NPCs that are clearly present and interacted with. Return an empty array if none.
         Narration: "${narration}"`,
        { world: { name: world.name, foundationalLaws: world.foundationalLaws ?? [], culturalTypologies: world.culturalTypologies ?? [] } },
        npcShape,
      );

      const npcs: any[] = extracted?.npcs ?? [];

      for (const npcData of npcs) {
        if (!npcData.name) continue;

        // Check if NPC already exists in this world
        const existing = await this.npcService.findByName(world.id, npcData.name);
        if (existing) {
          // Update their zone location
          await this.npcService.updateZone(existing.id, zone.id);
          continue;
        }

        // Create VedaEntity record
        const vedaEntity = await this.vedaService.saveEntity({
          worldId: world.id,
          zoneId: zone.id,
          name: npcData.name,
          entityType: 'NPC',
          description: npcData.physicalDescription ?? npcData.name,
        });

        // Create rich NPC record
        await this.npcService.create({
          worldId: world.id,
          vedaEntityId: vedaEntity.id,
          currentZoneId: zone.id,
          name: npcData.name,
          species: npcData.species !== 'null' ? npcData.species : undefined,
          race: npcData.race !== 'null' ? npcData.race : undefined,
          gender: npcData.gender !== 'null' ? npcData.gender : undefined,
          physicalDescription: npcData.physicalDescription,
          traits: Array.isArray(npcData.traits) ? npcData.traits : [],
          disposition: npcData.disposition ?? 'neutral',
          backstory: npcData.backstory !== 'null' ? npcData.backstory : undefined,
        });
      }
    } catch {
      // NPC extraction is best-effort — never fail the main action
    }
  }
}
